---
version: 2
jobs:
  build-jar:
    docker:
      - image: circleci/openjdk:11-jdk-sid
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: gradle test ktlintCheck
      - run: gradle shadowJar
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar
  build-docker:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: scripts/docker-auth.sh
      - run: scripts/docker-build-image.sh
      - run: scripts/docker-push-image.sh
workflows:
  version: 2
  my-workflow:
    jobs:
      - build-jar
      - build-docker:
          context: Docker Hub
          requires:
            - build-jar
