---
version: 2
jobs:
  build-jar:
    docker:
      - image: circleci/openjdk:11-jdk-sid
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: ./gradlew test ktlintCheck
      - run: ./gradlew shadowJar
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar
  build-and-publish-docker:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: scripts/docker-auth.sh
      - run: scripts/docker-build-image.sh
      - run: scripts/docker-test-image.sh
      - run: scripts/docker-push-image.sh
      - persist_to_workspace:
          root: .
          paths:
            - .dockerrepo
            - .dockertag
  deploy-prod:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "f4:52:63:45:e1:f9:17:89:61:f6:ba:0f:e7:65:a7:48"
      - run: scripts/deploy.sh
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-jar
      - build-and-publish-docker:
          context: Docker Hub
          requires:
            - build-jar
      - deploy-prod:
          filters:
            branches:
              only: master
          requires:
            - build-and-publish-docker
